let searchList = [
    {keywords: ["dog", "pet", "animal", "fluffy"], title: "Here is a dog", description: "The dog or domestic dog (Canis familiaris or Canis lupus familiaris) is a domesticated descendant of the wolf which is characterized by an upturning tail. The dog is derived from an ancient, extinct wolf, and the modern wolf is the dog's nearest living relative. The dog was the first species to be domesticated, by hunter–gatherers over 15,000 years ago, before the development of agriculture.", url: "https://en.wikipedia.org/wiki/Dog"},
    {keywords: ["cat", "pet", "animal", "fluffy"], title: "Here is a cat", description: "The cat (Felis catus) is a domestic species of a small carnivorous mammal. It is the only domesticated species in the family Felidae and is often referred to as the domestic cat to distinguish it from the wild members of the family. A cat can either be a house cat, a farm cat or a feral cat; the latter ranges freely and avoids human contact. Domestic cats are valued by humans for companionship and their ability to kill rodents. About 60 cat breeds are recognized by various cat registries.", url: "https://en.wikipedia.org/wiki/Cat"},
    {keywords: ["rabbit", "pet", "animal", "fluffy"], title: "Here is a rabbit",description: "Rabbits, also known as bunnies or bunny rabbits, are small mammals in the family Leporidae (which also contains the hares) of the order Lagomorpha (which also contains the pikas). Oryctolagus cuniculus includes the European rabbit species and its descendants, the world's 305 breeds of domestic rabbit. Sylvilagus includes 13 wild rabbit species, among them the seven types of cottontail. ", url: "https://en.wikipedia.org/wiki/Rabbit"},
    {keywords: ["horse", "pet", "animal", "large"], title: "Here is a Horse",description: "The horse (Equus ferus caballus) is a domesticated, odd-toed, hoofed mammal. It belongs to the taxonomic family Equidae and is one of two extant subspecies of Equus ferus. The horse has evolved over the past 45 to 55 million years from a small multi-toed creature, Eohippus, into the large, single-toed animal of today. Humans began domesticating horses around 4000 BC, and their domestication is believed to have been widespread by 3000 BC.", url: "https://en.wikipedia.org/wiki/Horse"},
    {keywords: ["fish", "pet", "animal", "scales"], title: "Here is a fish",description: "Fish are aquatic, craniate, gill-bearing animals that lack limbs with digits. Included in this definition are the living hagfish, lampreys, and cartilaginous and bony fish as well as various extinct related groups. Around 99% of living fish species are ray-finned fish, belonging to the class Actinopterygii, with over 95% belonging to the teleost subgrouping.", url: "https://en.wikipedia.org/wiki/Fish"},
    {keywords: ["rat", "pet", "animal", "fluffy"], title: "Here is a rat", description: "Rats are various medium-sized, long-tailed rodents. Species of rats are found throughout the order Rodentia, but stereotypical rats are found in the genus Rattus. Other rat genera include Neotoma (pack rats), Bandicota (bandicoot rats) and Dipodomys (kangaroo rats).", url: "https://en.wikipedia.org/wiki/Rat"},
    {keywords: ["mouse", "pet", "animal", "fluffy"], title: "Here is a mouse",description: "A mouse (pl: mice) is a small mammal. Characteristically, mice are known to have a pointed snout, small rounded ears, a body-length scaly tail, and a high breeding rate. The best known mouse species is the common house mouse (Mus musculus). Mice are also popular as pets. In some places, certain kinds of field mice are locally common. They are known to invade homes for food and shelter.", url: "https://en.wikipedia.org/wiki/Mouse"},
    {keywords: ["snake", "pet", "animal", "scales"], title: "Here is a snake",description: "Snakes are elongated, limbless, carnivorous reptiles of the suborder Serpentes /sɜːrˈpɛntiːz/. Like all other squamates, snakes are ectothermic, amniote vertebrates covered in overlapping scales. Many species of snakes have skulls with several more joints than their lizard ancestors, enabling them to swallow prey much larger than their heads with their highly mobile jaws.", url: "https://en.wikipedia.org/wiki/Snake"},
    {keywords: ["hamster", "pet", "animal", "fluffy"], title: "Here is a hamster",description: "Hamsters are rodents (order Rodentia) belonging to the subfamily Cricetinae, which contains 19 species classified in seven genera. They have become established as popular small pets. The best-known species of hamster is the golden or Syrian hamster (Mesocricetus auratus), which is the type most commonly kept as pets. Other hamster species commonly kept as pets are the three species of dwarf hamster, Campbell's dwarf hamster (Phodopus campbelli), the winter white dwarf hamster (Phodopus sungorus) and the Roborovski hamster (Phodopus roborovskii).", url: "https://en.wikipedia.org/wiki/Hamster"},
    {keywords: ["lizard", "pet", "animal", "scales"], title: "Here is a lizard", description: "Lizards (suborder Lacertilia) are a widespread group of squamate reptiles, with over 6,000 species,[1] ranging across all continents except Antarctica, as well as most oceanic island chains. The group is paraphyletic as it excludes the snakes and Amphisbaenia; some lizards are more closely related to these two excluded groups than they are to other lizards. Lizards range in size from chameleons and geckos a few centimeters long to the 3 meter long Komodo dragon.", url: "https://en.wikipedia.org/wiki/Lizard"}
]

module.exports = {
    searchList
}
